from __future__ import annotations

import json
import logging
import math
import os
import time
from dataclasses import dataclass
from enum import StrEnum
from typing import Any

logger = logging.getLogger(__name__)

STATUS_FILE = os.path.expanduser("~/.claude/usage-status.json")
LEGACY_STATUS_FILE = os.path.expanduser("~/.claude/usag-status.json")
TT_STATUS_FILE = os.path.expanduser("~/.claude/tt-status.json")
# Desktop-side usage status generated by claude_app_rate_loader.py on a
# LaunchAgent timer. Prefer this over Claude Code CLI statusLine output so the
# menubar reflects Claude.app usage when both files exist.
DERIVED_STATUS_FILE = os.path.expanduser("~/.claude/usage-status-derived.json")

# ステータスファイルの古さを警告するためのしきい値。数値表示そのものには影響しない。
STALE_SECONDS = 6 * 3600


class PollState(StrEnum):
    LOADING = "loading"
    SUCCESS = "success"
    TOKEN_ERROR = "token_error"
    CONNECTION_ERROR = "connection_error"
    RATE_LIMITED = "rate_limited"
    FATAL = "fatal"


@dataclass(slots=True)
class UsageSnapshot:
    current_percent: int | None
    current_reset_at: float
    weekly_percent: int | None
    weekly_reset_at: float
    current_status: str
    polled_at: float


@dataclass(slots=True)
class PollOutcome:
    state: PollState
    snapshot: UsageSnapshot | None = None
    message: str | None = None


def _pct(value: Any) -> int:
    numeric = _as_finite_float(value)
    if numeric is None:
        return 0
    return max(0, min(100, round(numeric)))


def _reset_at(value: Any, default: float) -> float:
    numeric = _as_finite_float(value)
    if numeric is None:
        return default
    return numeric


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_finite_float(value: Any) -> float | None:
    if isinstance(value, bool):
        return None
    try:
        numeric = float(value)
    except (TypeError, ValueError):
        return None
    return numeric if math.isfinite(numeric) else None


def _read_status_file() -> tuple[dict[str, Any], str] | None:
    """利用可能な status JSON を読む。Claude Desktop 推算ファイルを最優先にする。"""
    for path in (DERIVED_STATUS_FILE, STATUS_FILE, LEGACY_STATUS_FILE, TT_STATUS_FILE):
        if not os.path.exists(path):
            continue
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError):
            if os.environ.get("USAGE_DEBUG") == "1":
                logger.warning("failed to read status file %s", path, exc_info=True)
            continue
        if isinstance(data, dict):
            return data, path
        if os.environ.get("USAGE_DEBUG") == "1":
            logger.warning("status file %s is not a JSON object", path)
    return None


def _build_snapshot(data: dict[str, Any]) -> UsageSnapshot | None:
    rl = _as_dict(data.get("rate_limits"))
    five = _as_dict(rl.get("five_hour"))
    seven = _as_dict(rl.get("seven_day"))

    five_pct_raw = five.get("used_percentage")
    seven_pct_raw = seven.get("used_percentage")
    if five_pct_raw is None and seven_pct_raw is None:
        return None

    now = time.time()
    five_reset = _reset_at(five.get("resets_at"), now)
    seven_reset = _reset_at(seven.get("resets_at"), now)

    # リセット時刻を過ぎた表示は 0% に戻す。token-tracker と同じ考え方。
    five_pct = (
        0
        if five_reset and five_reset < now
        else _pct(five_pct_raw)
        if five_pct_raw is not None
        else None
    )
    seven_pct = (
        0
        if seven_reset and seven_reset < now
        else _pct(seven_pct_raw)
        if seven_pct_raw is not None
        else None
    )

    polled_at = _as_finite_float(data.get("_received_at_ts")) or now

    status = ""
    if isinstance(rl.get("status"), str):
        status = rl["status"]

    return UsageSnapshot(
        current_percent=five_pct,
        current_reset_at=five_reset,
        weekly_percent=seven_pct,
        weekly_reset_at=seven_reset,
        current_status=status,
        polled_at=polled_at,
    )


class ClaudeUsageClient:
    """ローカル JSON から Claude の使用量状態を読み取る。

    async インターフェースと interval_seconds は既存の polling ループに合わせて残している。
    実際の読み取りは同期処理だが、UI 側は interval を更新間隔として使う。
    """

    def __init__(self, *, interval_seconds: int = 60, mock: bool = False) -> None:
        self.interval_seconds = interval_seconds
        self.mock = mock

    async def aclose(self) -> None:
        return None

    async def fetch_once(self) -> PollOutcome:
        if self.mock:
            return self._mock_outcome()

        result = _read_status_file()
        if result is None:
            return PollOutcome(
                state=PollState.TOKEN_ERROR,
                message=(
                    "⚠ ステータスファイルが見つかりません。"
                    "`python3 main.py --setup` を実行して Claude Code を一度開いてください"
                ),
            )

        data, source_path = result
        snapshot = _build_snapshot(data)
        if snapshot is None:
            return PollOutcome(
                state=PollState.LOADING,
                message=(
                    "⚠ ステータスファイルに使用量データがまだありません。"
                    "Claude Code の statusLine 更新を待ってください"
                ),
            )

        now = time.time()
        is_stale = (now - snapshot.polled_at) > STALE_SECONDS
        if source_path == TT_STATUS_FILE:
            source_tag = "tt-status"
        elif source_path == DERIVED_STATUS_FILE:
            source_tag = "derived"
        else:
            source_tag = "usage"
        message = None
        if is_stale:
            mins = int((now - snapshot.polled_at) / 60)
            message = f"⚠ {source_tag} stale {mins}m"

        return PollOutcome(state=PollState.SUCCESS, snapshot=snapshot, message=message)

    def _mock_outcome(self) -> PollOutcome:
        now = time.time()
        return PollOutcome(
            state=PollState.SUCCESS,
            snapshot=UsageSnapshot(
                current_percent=50,
                current_reset_at=now + 82 * 60,
                weekly_percent=11,
                weekly_reset_at=now + ((6 * 24) + 8) * 3600,
                current_status="ok",
                polled_at=now,
            ),
            message=None,
        )
